### ISSUE TITLE
Can't jump to another path in first click

### ISSUE THREAD

**Issue by harrysun-code** [zqjimlove/angular-ueditor#1]
I use angular-ueditor like followings

``` html
<a href="/test">test</a>
...
<div class="ueditor" name="content" ng-model="content" ></div>
```

When I first click 'test' link, nothing happened. But, When I click it again, I can jump to the /test.
If I remove angular-ueditor, it will be normal.

**Comment by zqjimlove** [comment]
I tried `<a href="http://baidu.com">test</a>` with in demo page,but it's ok.

**Comment by harrysun-code** [comment]
Please try it with $location.

**Comment by zqjimlove** [comment]
All is right with $location @CraryPrimitiveMan
