### ISSUE TITLE
Firefox 浏览器通过输入法输入时无法触发contentchange 事件。

### ISSUE THREAD

**Issue by seamys** [zqjimlove/angular-ueditor#10]
Firefox 浏览器通过输入法输入时无法触发 contentChange  事件。
ueditor 编辑器在输入法输入时，没有触发 contentChange  模型绑定失效问题
![abc](https://cloud.githubusercontent.com/assets/7090368/12188400/edd75a08-b5ef-11e5-8c37-f4e979e015f9.gif)

**Comment by zqjimlove** [comment]
@seamys 试了一下最新版火狐并没有问题。可以提供一下版本号吗？

**Comment by seamys** [comment]
43.0.4 应该是Firefox 最新版本的。 只有在搜狗输入时【空格确定】时候回出现这个问题。目测是百度编辑器的兼容问题.
换成监听  wordCount 事件这个问题解决了。
不知道会不会出现其他问题
