### ISSUE TITLE
使用ue的execCommand更新内容会报错

### ISSUE THREAD

**Issue by yanqing6628780** [zqjimlove/angular-ueditor#11]
想请问下.我用
`$scope.ready = function(editor){
ue = editor;
}`
获得了实例
然后使用
`ue.execCommand('inserthtml', '+$scope.activeMediaImg.url+');`
在当前光标位置插入html内容.内容是插入成功了.不过还要对model重新赋值才生效
`$scope.activeNewsItem.content = ue.getContent();`
而且执行execCommand会报下面的错误
Error: [$rootScope:inprog] http://errors.angularjs.org/1.4.8/$rootScope/inprog?p0=%24apply
请问这是什么原因呢?

**Comment by zqjimlove** [comment]
因为我主要靠UE的contentChange的事件来更新 model，但貌似对于这个事件的触发UE没有很好的处理上。而且我把这个ISSUE提出来很久，但UE那边一直都没有更新。

**Comment by yanqing6628780** [comment]
@zqjimlove 多谢up主解答.既然没什么问题就先用着~有空我也研究研究
