### ISSUE TITLE
建议跟随scope销毁时，同时销毁ueditor对象

### ISSUE THREAD

**Issue by askie** [zqjimlove/angular-ueditor#14]
否则，会一直驻留内存中。

**Comment by zqjimlove** [comment]
$S.$on "$destroy", ->
                UE.delEditor _editorId if not attr.id && UE.delEditor
已经是做了处理的

**Comment by askie** [comment]
好像没有销毁，浏览器会报错这个：
![image](https://cloud.githubusercontent.com/assets/1140973/16371347/abe85b6e-3c78-11e6-81fe-917966b184e3.png)

**Comment by zqjimlove** [comment]
那这个有可能是ueditor本身在做销毁处理的时候并没有到位。可能主要对象是销毁了，但一些绑定的事件并没有处理，这个需要研究一下是否ueditor的问题了（毕竟它undefined是不是ue对象也很难说）。

**Comment by zqjimlove** [comment]
``` javascript
  //修复内容过多时，回到顶部，顶部内容被工具栏遮挡问题
        var lastScrollY;
        window.onscroll = function(){
            if(lastScrollY === null){
                lastScrollY = this.scrollY
            }else if(this.scrollY == 0 && lastScrollY != 0){
                me.window.scrollTo(0,0);
                lastScrollY = null;
            }
        }
```

这段代码报错的，ueditor已经销毁了。所以……是ueditor代码有点……嗯嗯
