### ISSUE TITLE
元素中不能出现id属性

### ISSUE THREAD

**Issue by alexgzhou** [zqjimlove/angular-ueditor#3]
报告一个问题:

div class="ueditor" id="whatever" name="post" ng-model="post.content" ready="ueReady" config="ueConfig" required

元素中不能出现id属性, 否则就报错Cannot read property 'length' of undefined, Cannot set property 'innerHTML' of null

**Comment by zqjimlove** [comment]
已经修复，但由于UEDitor会记录编辑状态所以需要重复使用时设置ID就好了

closed by commit 1ba71e5fcf54d363142176b73c58bf460562ab1c
