### ISSUE TITLE
上传图片 双向绑定 不更新

### ISSUE THREAD

**Issue by ghost** [zqjimlove/angular-ueditor#4]
你好
我使用 https://github.com/zhangfisher/DjangoUeditor
搭配您的这个 angular-ueditor 

---

可以上传图，但是，
比如，我就添加一张图，从我的剪贴板 直接粘贴，虽然编辑框里面图片已经上传成功 服务器也返回了图片网址了，可是 变量里面 存的还是 /ueditor/themes/default/images/spacer.gif  这个图
我必须，在编辑框输入其他内容，变量里的图片网址才会更新
## 或者我单击 编辑框里的图，变量里的图片网址才会更新

请问前辈  我该如何操作，我对js不太懂

**Comment by zqjimlove** [comment]
上传图片这个由于是UEditor更换了元素但没有触发update事件.暂时还没有很好的办法，只能修改UEditor的代码
