### ISSUE TITLE
angular配合route切换时出错，必须手动刷新才能正常初始化

### ISSUE THREAD

**Issue by julor** [zqjimlove/angular-ueditor#5]
源代码57行有错误：_self.modelContent这个值为空
angular报：Error: [$rootScope:inprog] $digest already in progress，位置在52行

**Comment by jaguarsy** [comment]
这个问题依旧存在

**Comment by zqjimlove** [comment]
已经修复
closed by commit 1ba71e5fcf54d363142176b73c58bf460562ab1c
