### ISSUE TITLE
压缩文件有错误

### ISSUE THREAD

**Issue by echizen** [zqjimlove/angular-ueditor#6]
我使用了你的v0.0.2压缩文件不能运行，但是不压缩的是可以的，你可能要看一下你压缩时是否损坏了

**Comment by seamys** [comment]
在百度编辑器使用搜狗输入法时，不按空格回车等其他键，无法触发 contentChange 事件。没有办法更新绑定的model。请问可以使用 wordcount 事件来监听编辑器变化吗？
